### ISSUE TITLE
Inconsistent use of playCount vs playcount

### ISSUE THREAD

**Issue by ridmaur** [tfmart/ScrobbleKit#2]
In some objects like `SBKTrack`, `playcount` attribute is used, in others, like `SBKArtistInfoGetData`,  `playCount`.
Is this on purpose?

**Comment by tfmart** [comment]
Hi @ridmaur, thanks for pointing this inconsistency. I'll make sure to update `SBKArtistInfoGetData` to follow the `playcount` naming like the rest of the project

**Comment by tfmart** [comment]
I've just released a [new version](https://github.com/tfmart/ScrobbleKit/releases/tag/1.0.1) that fixes the naming issue discussed here. Thanks for opening this issue!
