### ISSUE TITLE
playcount for Track / Album is of different type than playcount for ArtistGetInfoData

### ISSUE THREAD

**Issue by ridmaur** [tfmart/ScrobbleKit#5]
For Track / Album it is String, for ArtistGetInfoData it is Int.

**Comment by tfmart** [comment]
Hi @ridmaur, thank you for your feedback! We have released v1.0.2 to address the type property misalignment issues and include other improvements/patches. 

Check out the release notes [here](https://github.com/tfmart/ScrobbleKit/releases/tag/1.0.2).
