### ISSUE TITLE
How to get from AlbumResponse to Album?

### ISSUE THREAD

**Issue by ridmaur** [tfmart/ScrobbleKit#6]
Why is getting more info on an album giving me not an Album object back, but instead an AlbumResponse object. Disadvantage is that AlbumResponse is lacking listeners attribute, which Album does have.

**Comment by tfmart** [comment]
Hi @ridmaur, thanks for your feedback. I've addressed this issue on the latest release of ScrobbleKit (v1.0.2)

Check out the release notes [here](https://github.com/tfmart/ScrobbleKit/releases/tag/1.0.2).
