### ISSUE TITLE
Inconsistent type for URL across SBKAlbum, SBKTrack and SBKArtist

### ISSUE THREAD

**Issue by ridmaur** [tfmart/ScrobbleKit#7]
For SBKAlbum, URL is of type String?, for the others of type URL?

**Comment by tfmart** [comment]
Hi @ridmaur, thanks for opening this issue and sorry for taking a while to get back to you. I've released a new release `1.0.3` that updates the URL types from some public models to `URL`, to be inline with the rest of them
